// <auto-generated />
namespace StudentList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class index_required1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(index_required1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612012300052_index_required1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
